// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSensorLogEntry = "sensor"

// SensorLogEntry mapped from table <sensor>
type SensorLogEntry struct {
	Datetime    time.Time `gorm:"column:datetime;type:DATETIME;not null" json:"datetime"`
	Co2         *int32    `gorm:"column:co2;type:INTEGER" json:"co2"`
	Temperature *int32    `gorm:"column:temperature;type:INTEGER" json:"temperature"`
	Humidity    *int32    `gorm:"column:humidity;type:INTEGER" json:"humidity"`
	Pressure    *int32    `gorm:"column:pressure;type:INTEGER" json:"pressure"`
}

// TableName SensorLogEntry's table name
func (*SensorLogEntry) TableName() string {
	return TableNameSensorLogEntry
}
